server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.key
